name: publish
on:
  release:
    types: [ published ]

jobs:
  publish-crates-io:
      name: Publish to crates.io
      runs-on: ubuntu-latest
      
      steps:

        - uses: actions/checkout@v2

        - run: cargo publish --token ${{ secrets.CRATES_IO_API_TOKEN }}
