name: release
on: [ push ]
jobs:

  draft-release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_release.outputs.tag_name }}
    
    steps:
    
      - id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build
    runs-on: ${{ matrix.os }}
    needs: [draft-release]
    
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
         - os: ubuntu-latest
           target: aarch64-unknown-linux-musl
           use-cross: true
         - os: macos-latest
           target: x86_64-apple-darwin
         - os: windows-latest
           target: x86_64-pc-windows-gnu
           ext: .exe
    
    permissions:
      contents: write
      pull-requests: read
      
    steps:
    
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.use-cross }}
          args: --release --all-features --target ${{ matrix.target }}

      - run: gh release upload --clobber ${{ needs.draft-release.outputs.version }} ./target/${{ matrix.target }}/release/shreddit${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

