name: release
on: [ push ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          
      - run: pwd
 
      - run: gh release upload --clobber v0.1.0 ./target/release/shreddit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
