name: release
on: [ push ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [aarch64-unknown-linux-musl, x86_64-pc-windows-gnu]
    
    permissions:
      contents: write
      pull-requests: read
      
    steps:
    
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --all-features --target ${{ matrix.target }}

  release:
    name: release
    runs-on: ubuntu-latest
    
    steps:
    
      - id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: gh release upload --clobber ${{ steps.create_release.outputs.tag_name }}  ./target/release/shreddit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
