name: release
on: [ push ]
jobs:

  draft-release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_release.outputs.tag_name }}
    
    steps:
    
      - id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [draft-release]
    
    strategy:
      matrix:
        target: [aarch64-unknown-linux-musl, x86_64-pc-windows-gnu]
    
    permissions:
      contents: write
      pull-requests: read
      
    steps:
    
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --all-features --target ${{ matrix.target }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: shreddit-${{ matrix.target }}
          path: ./target/release/shreddit*

      - run: gh release upload --clobber ${{ needs.draft-release.outputs.version }} ./target/release/shreddit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

